M48
; DRILL file {KiCad (6.0.8)} date Fri Oct 21 01:17:31 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-21T01:17:31+13:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X-0.6604Y-0.4288
X-0.4288Y0.6604
X0.4288Y-0.6604
X0.6604Y0.4288
T0
M30
