M48
; DRILL file {KiCad 8.0.1} date 2025-06-23T19:48:17+1200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-06-23T19:48:17+12:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0228
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0787
%
G90
G05
T2
X5.9941Y-2.0531
T3
X5.315Y-0.8858
X5.315Y-3.0748
X6.378Y-0.8858
X6.378Y-3.0748
T1
G00X5.7071Y-2.0531
M15
G01X5.6906Y-2.0531
M16
G05
M30
